### ISSUE TITLE
False positive on tests without subtests

### ISSUE THREAD

**Issue by Nivl** [moricho/tparallel#8]
The linter fails when a test doesn't have substests.

Code:

```go
package testdata

import (
	"testing"
)

func TestSomething(t *testing.T) {
	t.Parallel()
}
```

Error:

```
no_subtests_test.go:7:6: TestSomething's subtests should call t.Parallel
```

Expectation:

No errors, or at the very least a different error message.

**Comment by moricho** [comment]
Thanks for reporting! I fixed that bug.

**Comment by moricho** [comment]
Thanks for reporting! I fixed that bug and released a new version.
https://github.com/moricho/tparallel/releases/tag/v0.2.1
